from typing import List, Dict, Any

CAMPUS_RESOURCES_SEED: List[Dict[str, Any]] = [
    {
        "resource_id": "central_library",
        "name": "Central Library",
        "type": "library",
        "building": "William Gates Academic Center",
        "floor": 2,
        "latitude": 37.774929,
        "longitude": -122.419416,
        "capacity": 300,
        "facilities": ["High-Speed WiFi", "Silent Study Pods", "Power Outlets", "Printing Station", "Research Desk"],
        "opening_time": "08:00",
        "closing_time": "23:00",
        "status": "open",
        "current_occupancy": 140,
        "occupancy_percentage": 46.7,
        "available_capacity": 160,
        "crowd_status": "MEDIUM"
    },
    {
        "resource_id": "computer_lab_1",
        "name": "Computer Lab 1 (High Perf)",
        "type": "computer_lab",
        "building": "Turing Engineering Hall",
        "floor": 1,
        "latitude": 37.775210,
        "longitude": -122.418750,
        "capacity": 60,
        "facilities": ["GPU Workstations", "Dual Monitors", "Linux/Windows Dual Boot", "Air Conditioned"],
        "opening_time": "08:30",
        "closing_time": "21:00",
        "status": "open",
        "current_occupancy": 38,
        "occupancy_percentage": 63.3,
        "available_capacity": 22,
        "crowd_status": "MEDIUM"
    },
    {
        "resource_id": "computer_lab_2",
        "name": "Computer Lab 2 (Software Dev)",
        "type": "computer_lab",
        "building": "Turing Engineering Hall",
        "floor": 2,
        "latitude": 37.775350,
        "longitude": -122.418650,
        "capacity": 50,
        "facilities": ["IDE Software Suites", "Whiteboards", "Power Outlets", "Projector"],
        "opening_time": "08:30",
        "closing_time": "20:00",
        "status": "open",
        "current_occupancy": 22,
        "occupancy_percentage": 44.0,
        "available_capacity": 28,
        "crowd_status": "MEDIUM"
    },
    {
        "resource_id": "computer_lab_3",
        "name": "Computer Lab 3 (Open Access)",
        "type": "computer_lab",
        "building": "Lovelace IT Commons",
        "floor": 1,
        "latitude": 37.774500,
        "longitude": -122.420100,
        "capacity": 75,
        "facilities": ["General Workstations", "Wireless Printing", "Scanner", "Ergonomic Chairs"],
        "opening_time": "07:30",
        "closing_time": "22:00",
        "status": "open",
        "current_occupancy": 18,
        "occupancy_percentage": 24.0,
        "available_capacity": 57,
        "crowd_status": "LOW"
    },
    {
        "resource_id": "study_room_a",
        "name": "Study Room A (Collaborative)",
        "type": "study_room",
        "building": "Student Union Building",
        "floor": 3,
        "latitude": 37.774100,
        "longitude": -122.419200,
        "capacity": 20,
        "facilities": ["Smart TV Display", "Whiteboard Wall", "Conference Mic", "Power Sockets"],
        "opening_time": "08:00",
        "closing_time": "22:00",
        "status": "open",
        "current_occupancy": 6,
        "occupancy_percentage": 30.0,
        "available_capacity": 14,
        "crowd_status": "LOW"
    },
    {
        "resource_id": "study_room_b",
        "name": "Study Room B (Quiet Zone)",
        "type": "study_room",
        "building": "Student Union Building",
        "floor": 3,
        "latitude": 37.774150,
        "longitude": -122.419250,
        "capacity": 25,
        "facilities": ["Noise-Dampening Panels", "Standing Desks", "LED Task Lights", "USB-C Ports"],
        "opening_time": "08:00",
        "closing_time": "22:00",
        "status": "open",
        "current_occupancy": 19,
        "occupancy_percentage": 76.0,
        "available_capacity": 6,
        "crowd_status": "HIGH"
    },
    {
        "resource_id": "study_room_c",
        "name": "Study Room C (Group Discussion)",
        "type": "study_room",
        "building": "William Gates Academic Center",
        "floor": 1,
        "latitude": 37.774800,
        "longitude": -122.419600,
        "capacity": 15,
        "facilities": ["Interactive Touchscreen", "Modular Desks", "WiFi 6"],
        "opening_time": "09:00",
        "closing_time": "21:00",
        "status": "open",
        "current_occupancy": 5,
        "occupancy_percentage": 33.3,
        "available_capacity": 10,
        "crowd_status": "LOW"
    },
    {
        "resource_id": "classroom_a",
        "name": "Classroom A (Tiered Hall)",
        "type": "classroom",
        "building": "Main Lecture Complex",
        "floor": 1,
        "latitude": 37.775800,
        "longitude": -122.419000,
        "capacity": 120,
        "facilities": ["Dual Projectors", "Surround Audio", "Podium Controls", "Tiered Seating"],
        "opening_time": "08:00",
        "closing_time": "19:00",
        "status": "open",
        "current_occupancy": 85,
        "occupancy_percentage": 70.8,
        "available_capacity": 35,
        "crowd_status": "HIGH"
    },
    {
        "resource_id": "classroom_b",
        "name": "Classroom B (Seminar Style)",
        "type": "classroom",
        "building": "Main Lecture Complex",
        "floor": 2,
        "latitude": 37.775850,
        "longitude": -122.419050,
        "capacity": 80,
        "facilities": ["Interactive Whiteboard", "Hybrid Zoom Station", "Air Conditioning"],
        "opening_time": "08:00",
        "closing_time": "19:00",
        "status": "open",
        "current_occupancy": 28,
        "occupancy_percentage": 35.0,
        "available_capacity": 52,
        "crowd_status": "LOW"
    },
    {
        "resource_id": "main_cafeteria",
        "name": "Main Cafeteria & Food Court",
        "type": "cafeteria",
        "building": "Campus Dining Center",
        "floor": 1,
        "latitude": 37.773800,
        "longitude": -122.418500,
        "capacity": 250,
        "facilities": ["Hot Meal Counters", "Coffee Barista Station", "Outdoor Patio", "Self-Checkout"],
        "opening_time": "07:00",
        "closing_time": "21:30",
        "status": "open",
        "current_occupancy": 195,
        "occupancy_percentage": 78.0,
        "available_capacity": 55,
        "crowd_status": "HIGH"
    },
    {
        "resource_id": "seminar_hall",
        "name": "Grand Seminar Hall",
        "type": "seminar_hall",
        "building": "Auditorium Wing",
        "floor": 1,
        "latitude": 37.776100,
        "longitude": -122.419800,
        "capacity": 400,
        "facilities": ["Stage Lighting", "Concert Grade PA", "Live Stream Cameras", "Green Room"],
        "opening_time": "09:00",
        "closing_time": "22:00",
        "status": "open",
        "current_occupancy": 45,
        "occupancy_percentage": 11.3,
        "available_capacity": 355,
        "crowd_status": "LOW"
    }
]


async def seed_initial_resources(repo) -> None:
    """Seeds default campus resources if repository is currently empty."""
    existing = await repo.get_all()
    if not existing:
        for res in CAMPUS_RESOURCES_SEED:
            await repo.set(res["resource_id"], res)
